@startuml

interface IJasaPengiriman {
 +hitungOngkir(double jarak, double berat)
 +terimaRequestPemesanan(DetailPemesanan dp): Resi
}

class Ecommerce {
 +kirimRequestPengiriman(DetailPemesanan dp)
}

class JasaPengiriman {
 +idJasaPengiriman: int
 +nama: String
 +hitungOngkir(double jarak, double berat)
 +terimaRequestPemesanan(DetailPemesanan dp): Resi
}

class JNE {
 +hitungOngkir(double jarak, double berat)
 +terimaRequestPemesanan(DetailPemesanan dp): Resi 
}

class JNT {
 +hitungOngkir(double jarak, double berat)
}

@enduml
