@startuml

skinparam classAttributeIconSize 0
/'
menonaktifkan skin bawaan dari plantUML untuk access modifier (public, private, protected)
'/

class ECommerce{
    'atribut'
    +idEcommerce: int
    +namaEcommerce: String
    
    'method'
    +support(multipleDelivery)
}

class JNE{
    'atribut'
    -asalPengiriman: String
    -tujuanPengiriman: String
    -beratPengiriman: int

    'method'
    +reqPengiriman(): String
    +tarifPengiriman(
        asalPengiriman: String, 
        tujuanPengiriman: String, 
        beratPengiriman: int
    ): int
}

class JNT{
    'atribut'
    -asalPengiriman: String
    -tujuanPengiriman: String
    -beratPengiriman: int

    'method'
    +reqPengiriman(): String
    +tarifPengiriman(
        asalPengiriman: String, 
        tujuanPengiriman: String, 
        beratPengiriman: int
    ): int
}

class SiCepat{
    'atribut'
    -asalPengiriman: String
    -tujuanPengiriman: String
    -beratPengiriman: int

    'method'
    +reqPengiriman(): String
    +tarifPengiriman(
        asalPengiriman: String, 
        tujuanPengiriman: String, 
        beratPengiriman: int
    ): int
}

interface APIdelivery {
    'method'
    +{abstract} reqPengiriman(noInvoice: boolean)
    +{abstract} tarifPengiriman(
        asalPengiriman: String, 
        tujuanPengiriman: String, 
        beratPengiriman: int
    )
}

JNE ..|> APIdelivery
JNT ..|> APIdelivery
SiCepat ..|> APIdelivery
ECommerce <-- APIdelivery

Shipment *-- Order : composition

class Order {
   +orderID : Integer
   +dateOrderPlaced : date
   +totalValue : Integer
   +recipient : String
   +deliveryAddress : String
   +contactPhone : Integer
   +getCustomerinfo() : String
}

class Shipment {
   +shipmentID : Integer
   +shipmentCompany : String
   +trackingNumber : String
   +recipient : String
   +contactPhone : Integer
   +deliveryAddress : String
   +fee : Integer
   +timePickedUp : date
   +timeDelivered : date
   +sent() : boolean
}


@enduml
