@startuml Main
class Ecommerce {
    - weight int
    - quantity int
    - price int
    - destination string
    - source string
    + getTarif(weight, quantity, price, source, destination) void
    + getPickup(weight, quantity, price, expname, source, destination) void
}

interface Expedition {
/' #TODO: Populate '/
}

class Jne {
/' #TODO: Populate '/
}

class Jnt {
/' #TODO: Populate '/
}

class Sicepat {
/' #TODO: Populate '/
}

/' TODO: Add diagram link '/


@enduml