@startuml Main

Ecommerce --  Expedition
Expedition <|-- Jnt
Expedition <|-- Jne
Expedition <|-- Sicepat
class Ecommerce {
    - weight int
    - quantity int
    - price int
    - destination string
    - source string
    + getTarif(weight, quantity, price, source, destination) void
    + getPickup(weight, quantity, price, expname, source, destination) void
}

interface Expedition {
    +returnTarif()
    +menerimaRequest()
}

class Jne {
    - pilihan_jasa string
    - layanan_jasa string
    + returnTarif(weight, source, destination, Expedition) void
    + menerimaRequest (source, destination) void
}

class Jnt {
    - pilihan_jasa string
    - layanan_jasa string
    + returnTarif(weight, source, destination, Expedition) void
    + menerimaRequest (source, destination) void
}

class Sicepat {
    - pilihan_jasa string
    - layanan_jasa string
    + returnTarif(weight, source, destination, Expedition) void
    + menerimaRequest (source, destination) void
}




@enduml
