@startuml E-commerce
' diagram style

' diagram relation
DeliveryApi <|-- Sicepat
DeliveryApi <|-- JNE
DeliveryApi <|-- JNT
Store --> DeliveryApi

class Store{
  -String namaToko
  -String namaProduk
  -String tipeProduk
  -Float beratProduk
  -Double harga
  -String pembeli
  -String asal
  -String tujuan
  -String[] ekspedisi = {"Sicepat", "JNE", "JNT"};

  +void cekTarif(String tipeProduk, String asal, String tujuan, Float beratProduk)
  +void pesanProduk(String namaToko, String namaProduk, String tipeProduk, Float beratProduk, Double harga, String pembeli, String asal, String tujuan)
}

interface DeliveryApi{
    +tarifPengiriman(jarak,berat): Int
    +requestPengiriman(asal,tujuan) : String
}

Class Sicepat{
    -String idPengiriman
	  -String alamatPenerima
	  -Date tanggalPengiriman
	  -String namaPengirim 
	  -String namaPenerima
	  -String jenisProduk
	  -Float berat
	  -String statusPengiriman
  
    +tarifPengiriman(jarak,berat): Int
    +requestPengiriman(asal,tujuan) : String
}

Class JNE{
    -String idPengiriman
	  -String alamatPenerima
	  -Date tanggalPengiriman
	  -String namaPengirim 
	  -String namaPenerima
	  -String jenisProduk
  	-Float berat
  	-String statusPengiriman
  
    +tarifPengiriman(jarak,berat): Int
    +requestPengiriman(asal,tujuan) : String
}

Class JNT{
    -String idPengiriman
	  -String alamatPenerima
	  -Date tanggalPengiriman
	  -String namaPengirim 
	  -String namaPenerima
	  -String jenisProduk
	  -Float berat
	  -String statusPengiriman
  
    +tarifPengiriman(jarak,berat): Int
    +requestPengiriman(asal,tujuan) : String
}

@enduml
