@startuml E-commerce
' diagram style

' diagram relation
DeliveryApi <|-- Sicepat
DeliveryApi <|-- JNE
DeliveryApi <|-- JNT
Store --> DeliveryApi

class Store{
  -Sting storeName
  -String productName
  -String productType
  -Float productWight
  -Double price
  -String buyer
  -String origin
  -String destination
  -String[] expedition = {"Sicepat", "JNE", "JNT"};

  +void shippingRate(String productType, String origin, String destination, Float productWeight)
  +void requestSend(Sting storeName, String productName, String productType, Float productWight, Double price, String buyer, String origin, String destination)
}

interface DeliveryApi{
    +tarifPengiriman(jarak,berat): Int
    +requestPengiriman(asal,tujuan) : String
}

Class Sicepat{
    -String idPengiriman
	  -String alamatPenerima
	  -Date tanggalPengiriman
	  -String namaPengirim 
	  -String namaPenerima
	  -String jenisProduk
	  -Float berat
	  -String statusPengiriman
  
    +tarifPengiriman(jarak,berat): Int
    +requestPengiriman(asal,tujuan) : String
}

Class JNE{
    -String idPengiriman
	  -String alamatPenerima
	  -Date tanggalPengiriman
	  -String namaPengirim 
	  -String namaPenerima
	  -String jenisProduk
  	-Float berat
  	-String statusPengiriman
  
    +tarifPengiriman(jarak,berat): Int
    +requestPengiriman(asal,tujuan) : String
}

Class JNT{
    -String idPengiriman
	  -String alamatPenerima
	  -Date tanggalPengiriman
	  -String namaPengirim 
	  -String namaPenerima
	  -String jenisProduk
	  -Float berat
	  -String statusPengiriman
  
    +tarifPengiriman(jarak,berat): Int
    +requestPengiriman(asal,tujuan) : String
}

@enduml
